# Generated by Django 3.1 on 2021-02-13 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbnails/')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=256)),
                ('link', models.URLField(max_length=500)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvce.year')),
            ],
        ),
    ]
