# Generated by Django 3.1 on 2021-02-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='image',
            field=models.URLField(max_length=100),
        ),
    ]
