# Generated by Django 3.1 on 2021-02-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvce', '0003_auto_20210213_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
