# Generated by Django 3.1.3 on 2021-02-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bvce', '0005_auto_20210213_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('link', models.URLField(max_length=250, null=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvce.year')),
            ],
        ),
    ]
